# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b9e6efabb99c7f1d4e4e521ff8f96c08cfc3c3562a7cbe1c34cc303d0518d03e9e464b65bf221751e97b5c9c082f80035d2d87d6f799e2fadda3dad181426c

test:
  secret_key_base: 972a90c01e303cee9f36ff4535cb34fae975cc83f0611e22c81e814b65d9f89e85b81e1ebf6dfc6e7eaaa19d6ec40f2c5d8d0b63873f0798c9c97963ceddaac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
